from typing import Any
from pfcompass.rules.base import PFHealthRule, RuleContext, RuleEvidence, RuleResult


class UANMultiplicityRule(PFHealthRule):
    """PFH-004: Detect multiple active UAN numbers assigned to a single citizen."""

    def __init__(self, parameters: dict[str, Any] | None = None):
        params = parameters or {}
        self._max_allowed: int = params.get("max_allowed_uans", 1)

    @property
    def rule_id(self) -> str:
        return "PFH-004"

    @property
    def version(self) -> str:
        return "1.0.0"

    @property
    def domain(self) -> str:
        return "HEALTH"

    def evaluate(self, context: RuleContext) -> RuleResult:
        uan_count = len(context.uan_records)
        if uan_count <= self._max_allowed:
            return self._no_finding()

        uans_list = [str(u.get("uan")) for u in context.uan_records]

        return RuleResult(
            rule_id=self.rule_id,
            rule_version=self.version,
            triggered=True,
            severity="CRITICAL",
            what_is_wrong=f"Multiple UANs ({uan_count}) detected for your profile: {', '.join(uans_list)}.",
            why_it_happened="A new UAN was generated by a new employer instead of linking your existing active UAN.",
            potential_impact="Service fragmentation prevents automatic pension calculations and delays tax exemption eligibility.",
            correction_path={
                "summary": "Initiate UAN consolidation request.",
                "form_numbers": ["UAN-MERGE", "FORM-13"],
                "estimated_days": 30,
                "steps": [
                    "Select your primary active UAN.",
                    "Submit an online UAN merge request via EPFO Member Portal.",
                    "Transfer funds from secondary UAN accounts to your primary UAN."
                ]
            },
            evidence=[
                RuleEvidence(
                    field="uan_records.count",
                    expected=str(self._max_allowed),
                    actual=str(uan_count),
                    source="uan_records",
                    description=f"Citizen has {uan_count} UAN records registered ({', '.join(uans_list)})."
                )
            ],
            affected_account_ids=[],
            affected_employment_ids=[]
        )
